# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

#MY OWN DETAILS
gems: [jekyll-paginate, jekyll-gist]
kramdown:
  input: GFM
  syntax_highlighter: rouge
#END

# Setup
title:               IndeseabÎ»es 
tagline:             ''
description:         ''
url:                 http://indeseables.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Indeseables
  url:               https://twitter.com/indeseables
  email:             indeseables@gmail.com

# Custom vars
version:             
