# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

#MY OWN DETAILS
gems: [jekyll-paginate, jekyll-gist]
kramdown:
  input: GFM
  syntax_highlighter: rouge
#END

# Setup
title:               IndeseabÎ»es 
tagline:             ''
description:         ''
url:                 http://indeseables.github.io
baseurl:             ''
paginate:            3

# About/contact
author:
  name:              Indeseables
  url:               NOP
  email:             indeseables.git@gmail.com

# Custom vars
version:   1.1    

pages_list:
    About: '/about'
    Entradas: '/archive'
    Tags: '/tags'
    RSS: '/atom.xml'
    

authors:
  Overxfl0w13:
    display_name: overxfl0w13
    img: http://1.bp.blogspot.com/_CpVlf6p-G4c/TH5mw6_BsWI/AAAAAAAANIY/S5FXvav-7BA/s400/zayno-luffy_tux-15245.png
    email: overxfl0w13@hotmail.com
    web: http://indeseables.github.io
    twitter: NOP
    github: http://github.com/overxfl0w
    pgp: https://github.com/Indeseables/indeseables.github.io/tree/master/_keys/overxfl0w.pgp
    pgpid: D3297C4F
    
  Blau:
    display_name: Blau
    img: https://upload.wikimedia.org/wikipedia/commons/e/e8/Game_of_life_boat.png
    email: NOP
    web: http://indeseables.github.io
    twitter: NOP
    github: https://github.com/blau72
    pgp: NOP
    pgpid: NOP
    
  Sanko:
    display_name: Sanko
    img: https://upload.wikimedia.org/wikipedia/commons/e/e8/Game_of_life_boat.png
    email: NOP
    web: http://indeseables.github.io
    twitter: https://twitter.com/sankosk
    github: http://github.com/sankosk
    pgp: NOP
    pgpid: NOP
    
  Scorpio:
    display_name: Scorpio
    img: https://upload.wikimedia.org/wikipedia/commons/e/e8/Game_of_life_boat.png
    email: NOP
    web: http://indeseables.github.io
    twitter: NOP
    github: https://github.com/ScorpioTM
    pgp: NOP
    pgpid: NOP
    
  Sadfud:
    display_name: Sadfud
    img: https://upload.wikimedia.org/wikipedia/commons/e/e8/Game_of_life_boat.png
    email: NOP
    web: http://indeseables.github.io
    twitter: NOP
    github: NOP
    pgp: NOP
    pgpid: NOP
